### PR TITLE
make driver independent from mostjs

### PR DESCRIPTION
**Pull request by fiatjaf**
@mstn's revolution.

### CODE REVIEW

**Comment by SteveALee** [comment]
Is this nearly complete? I'm using xstream. Thanks

**Comment by fiatjaf** [comment]
@SteveALee complete now (at https://npmjs.com/package/cycle-graphql-driver). I'm not using this new version yet, however, but it should work. Please let us know if you find any bugs.

**Comment by SteveALee** [comment]
Thanks will do. Am new to graphQL so could be some false bugs :)

Should add this driver to cycle community repo on Github if not already.

**Comment by fiatjaf** [comment]
I've tried to put my packages in this community in the past, but they required me to create a ton of tests and screenshots and documentation.

**Comment by fiatjaf** [comment]
Use 0.4.2, please, @SteveALee.

**Comment by mstn** [comment]
If we join forces, maybe we will be luckier ;)

Imo we could have better chances if the package is rewritten in typescript since other packages do the same. It is not a big deal. If you have never done it before, I can setup a skeleton for the package.

I added a simple test as example in this project. With some more tests we should have a good coverage.

I was also thinking that the driver should return a queryable collection of observers [(see doc here)](https://cycle.js.org/drivers.html). A sort of lazy data structure as they did for vdom.

It would be cool if we can create a small demo like [GitHunt-angular2](https://github.com/apollostack/GitHunt-angular2/) or similars.

**Comment by fiatjaf** [comment]
I'm in a bad position for this thing, I can't even run the Typescript transpiler on any of my computers, but if you have good ideas I encourage you to implement them. This package is small enough to be easily rewritten in Typescript, I think (isn't it?).

i don't like the current way of getting the responses from GraphQL queries, although it is inspired by the HTTP driver. I can see it working being much better as a queryable collection of observers.

**Pull request merged**
